### ISSUE TITLE
DATA 550 final project peer review feedback

### ISSUE THREAD

**Issue by akshaydeverakonda** [kohguma/Chronic-Kidney-Final-Project#1]
Hi Michelle,

Your code looks great! Great organization overall. A couple issues though- your makefile is empty! I didn't see any code there. I manually ran your analysis from the different R chunks. Also, I can tell that you're creating the outputs and they're appearing in the output folder, it's just they're not actually showing up in the final report.  You're importing them successfully in the chronic_kidney_module5.rmd file that creates the report, you just need to add a couple lines of code to your chunks in chronic_kidney_module5.rmd to actually display them. 

Best,
Akshay

**Comment by kohguma** [comment]
Thank you! I was able to fill up the makefile and fixed all the other issues!
