### ISSUE TITLE
DATA550 final project peer review

### ISSUE THREAD

**Issue by L9otus** [kohguma/Chronic-Kidney-Final-Project#2]
Hi Michelle,
Your Makefile file seems to be empty. 
I ran code/01_ckd_output.R manually and three .rds file were successfully generated.
Then I ran code/01_ckd_render_report.R, the html file was generated but it didn't contain any table or figure. A few more lines of code are needed to let these visuals be printed out.
Aside from above issues, you did a great job!
Best,
Xiaohan

**Comment by kohguma** [comment]
Thank you! Made the makefile and updated everything :)
